---
title: "Contract Counties"
author: "Hanna Buechi"
date: "11/12/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r data_packages}

library(tidyverse)
wildfire_damage <- read_csv("fire17_1_1979-2017_damage_final.csv")

wildfire_damage <- wildfire_damage %>%
     mutate(DPA_rb=replace(DPA_rb, DPA_rb=="CALFIRE", "CDF"))

```

```{r filter_cco}

# filter out the CCO fires using "AGENCY"

cco1 <- wildfire_damage %>% 
  filter(AGENCY == "CCO")

# does this capture CC fires from the Redbook dataset, too?

cco2 <- wildfire_damage %>% 
  filter(DPA_rb == "CC") 

# this only has 75 entries, so I can check them easily against cco1 by hand (or by OID)
# just check by hand and then move to Google Drive... I have better things to do with my time than figure it out in R right now...

write_csv(cco1, path = "cco1.csv")

write_csv(cco2, path = "cco2.csv")

# There are 16 fires that are in cco2 (redbooks) and not cco1 (spatial)

# Which acres (redbooks or spatial) should I account for as CCO?

```

