---
title: "WUI and Cal Fire overlap"
author: "Hanna Buechi"
date: "10/30/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r data_packages}

library(tidyverse)
library(readr)

wildfire_damages <- read_csv("fire17_1_1979-2017_damage_TableToExcel.csv")
calfire_data <- read_csv("calfire_data.csv")

```

```{r WUI_overlap_data}

WUI_fires_1990 <- read_csv("WUI90_7995_fires_TabletoExcel.csv")

WUI_fires_2000 <- read_csv("WUI00_9606_fires_TabletoExcel.csv")

WUI_fires_2010 <- read_csv("WUI10_0717_fires_TabletoExcel.csv")

```

```{r WUI_1990}

sum(WUI_fires_1990$WUI_area) # 313,047 acres
nrow(WUI_fires_1990) # 1259 fires

sum(WUI_fires_1990$Total_dama) #3,097


```

```{r WUI_2000}

sum(WUI_fires_2000$WUI_area) # 219,926 acres
nrow(WUI_fires_2000) # 772 fires

sum(WUI_fires_2000$Total_dama) # 8,740 structures

```

```{r WUI_2010}

sum(WUI_fires_2010$WUI_area) # 1,046,894 acres
nrow(WUI_fires_2010) # 3,181 fires

sum(WUI_fires_2010$Total_dama) # 35,503 structures

```

```{r yearly_WUI}

structures_WUI90 <- WUI_fires_1990 %>% 
  group_by(YEAR1) %>% 
  summarise(Structures = sum(Total_dama))

acres_WUI90 <- WUI_fires_1990 %>% 
  group_by(YEAR1) %>% 
  summarise(WUI_acres = sum(WUI_area))

structures_WUI00 <- WUI_fires_2000 %>% 
  group_by(YEAR1) %>% 
  summarise(Structures = sum(Total_dama))

acres_WUI00 <- WUI_fires_2000 %>% 
  group_by(YEAR1) %>% 
  summarise(WUI_acres = sum(WUI_area))

structures_WUI10 <- WUI_fires_2010 %>% 
  group_by(YEAR1) %>% 
  summarise(Structures = sum(Total_dama))

acres_WUI10 <- WUI_fires_2010 %>% 
  group_by(YEAR1) %>% 
  summarise(WUI_acres = sum(WUI_area))
```

